### ISSUE TITLE
mod not working on server using 1.16.5 1.0.1

### ISSUE THREAD

**Issue by BlackcatCXII** [Chocorean/authmod#45]
<html>
<body>

[07Sep2021 10:26:54.275] [modloading-worker-0/ERROR] [AuthMod/CATCHING]: Catching
--
118 | com.electronwill.nightconfig.core.io.WritingException: An I/O error occured
119 | at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:222) ~[core-3.6.3.jar:?]
120 | at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.3.jar:?]
121 | at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.3.jar:?]
122 | at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.3.jar:?]
123 | at io.chocorean.authmod.config.Config.loadConfig(Config.java:113) ~[authmod:1.16.5-1.0.1]
124 | at io.chocorean.authmod.config.Config.loadConfig(Config.java:101) ~[authmod:1.16.5-1.0.1]
125 | at io.chocorean.authmod.AuthMod.<init>(AuthMod.java:27) ~[authmod:1.16.5-1.0.1]
126 | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_282]
127 | at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_282]
128 | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_282]
129 | at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_282]
130 | at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_282]
131 | at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2]
132 | at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?]
133 | at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_282]
134 | at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) [?:1.8.0_282]
135 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_282]
136 | at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_282]
137 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_282]
138 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_282]
139 | Caused by: java.nio.file.NoSuchFileException: /server/world/serverconfig/authmod-server.toml
140 | at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_282]
141 | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_282]
142 | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_282]
143 | at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_282]
144 | at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_282]
145 | at java.nio.file.Files.createFile(Files.java:632) ~[?:1.8.0_282]
146 | at com.electronwill.nightconfig.core.file.FileNotFoundAction.lambda$static$0(FileNotFoundAction.java:34) ~[core-3.6.3.jar:?]
147 | at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:215) ~[core-3.6.3.jar:?]
148 | ... 19 more

</body>
</html>

**Comment by Chocorean** [comment]
Can you join you config file?

**Comment by BlackcatCXII** [comment]
[authmod-server.toml](https://github.com/Chocorean/authmod/files/7122262/authmod.settings.txt)

yes i have access

**Comment by Kimapr** [comment]
i have the same issue
